- title: Reviewer
  description: "ICML (2024, 2025) · NeurIPS (2024, 2025) · ICLR (2025, 2026) · ACL Rolling Review (2024, 2025)"

- title: "President, AI Safety Group"
  description: University of Southern California

- title: Student Organizer
  description: "Center for Optimization and Statistical Learning, Northwestern University"
